version: "3"
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    depends_on:
      - mysql
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_PORT=5678
      # - NODE_ENV=production
      # - WEBHOOK_URL=http://${SUBDOMAIN}.${DOMAIN_NAME}/
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}

      - DB_TYPE=mysqldb
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_USER=n8n
      - DB_MYSQLDB_PASSWORD=my_secret_password
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
    links:
      - mysql
    networks:
      - n8n-net
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_password
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD=my_secret_password
    volumes:
      - /Users/samzonglu/deploy/n8n/mysql-data:/var/lib/mysql
      - /Users/samzonglu/deploy/n8n/conf.d:/etc/mysql/conf.d
    networks:
      - n8n-net
networks:
  n8n-net:
