remote_write:
  - url: http://127.0.0.1:8428/api/v1/write

global:
  scrape_interval: 3s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: contour
    static_configs:
      - targets: ["docker.for.mac.host.internal:50965"]
  - job_name: envoy
    static_configs:
      - targets: ["docker.for.mac.host.internal:63534"]
    metrics_path: "/stats/prometheus"
