version: "3"
services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    environment:
      - env=Mac
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ${DATA_FOLDER}/catalog:/etc/trino/catalog
      - ${DATA_FOLDER}/config.properties:/etc/config.properties
