version: "3"
services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    environment:
      - foo=bar
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_FOLDER}/catalog:/etc/trino/catalog
      - ${DATA_FOLDER}/data:/etc/trino/pemdata
      - ${DATA_FOLDER}/jvm.config:/etc/jvm.config
      - ${DATA_FOLDER}/config.properties:/etc/config.properties
