version: "3"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  env_file: /Users/samzonglu/deploy/redash.io/env
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5050:5000"
    environment:
      REDASH_WEB_WORKERS: 1
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 1
  redis:
    image: redis:5.0-alpine
  postgres:
    image: postgres:9.6-alpine
    env_file: /Users/samzonglu/deploy/redash.io/env
    volumes:
      - /Users/samzonglu/deploy/redash.io/postgres-data:/var/lib/postgresql/data
