apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-vector'
  labels:
    katenary.io/component: vector
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 5bd73d6912b8e7ab9e6808cd787c4ce9f8f10950
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: vector
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 9598
      targetPort: 9598
    - protocol: TCP
      port: 8686
      targetPort: 8686
